package:
  name: ogcore
  version: 0.5.13

source:
  path: ..

requirements:
  build:
    - python
    - "paramtools>=0.7.1"
    - setuptools
    - "scipy>=0.18.1"
    - matplotlib
    - "dask>=0.20.0"
    - mkl
    - requests

  run:
    - python
    - "paramtools>=0.7.1"
    - setuptools
    - "scipy>=0.18.1"
    - matplotlib
    - "dask>=0.20.0"
    - mkl
    - requests

about:
  home: https://github.com/PSLmodels/OG-Core/

test:
  imports:
    - ogcore
    - ogcore.SS
    - ogcore.TPI
    - ogcore.aggregates
    - ogcore.constants
    - ogcore.elliptical_u_est
    - ogcore.execute
    - ogcore.firm
    - ogcore.fiscal
    - ogcore.household
    - ogcore.output_plots
    - ogcore.output_tables
    - ogcore.parameter_plots
    - ogcore.parameter_tables
    - ogcore.parameters
    - ogcore.tax
    - ogcore.txfunc
    - ogcore.utils
    - ogcore.wealth
